import React from "react";
import type { Metadata } from "next";
import "./globals.css";
import PrelineScript from "../components/PrelineScript";
import Header from "../components/Header";
import Footer from "../components/Footer";

export const metadata: Metadata = {
  title: "Mountain View Chamber of Commerce",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>): React.JSX.Element {
  return (
    <html lang="en" className="light">
      <body className="light">
        <Header />
        {children}
        <Footer />
      </body>
      <PrelineScript />
    </html>
  );
}
